"use server";

import { createClient } from "@/lib/database/server";
import { InviteService } from "@/lib/services/invite/invite_service";
import { Invite } from "@/lib/types/database_types";

export async function sendLeagueInvite(formData: FormData) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "You must be logged in to send invites" };
  }

  const email = formData.get("email") as string;
  const leagueId = formData.get("leagueId") as string;

  if (!email || !leagueId) {
    return { error: "Email and league ID are required" };
  }

  const invite: Invite = {
    // id: is generated by the database
    league_id: leagueId,
    email,
    invited_by: user.id,
    // token: is generated by the database
    status: "pending",
    // expires_at: is generated by the database
    // created_at: is generated by the database
  };

  const { data, error } = await InviteService.createAndSendInvite(invite);

  if (error) {
    return { error: (error as string) || "An error occurred" };
  }

  return { success: true, data };
}

export async function createGenericInviteLink(
  leagueId: string,
  userId: string,
  maxUses: number
) {
  const { data, error } = await InviteService.createGenericInviteLink(
    leagueId,
    userId,
    maxUses
  );

  if (error) {
    return {
      error: error.message || "An error occurred creating the invite link",
    };
  }

  return { success: true, data };
}

export async function generateGenericInviteUrl(leagueId: string) {
  const { data, error } =
    await InviteService.generateGenericInviteUrl(leagueId);

  if (error) {
    return { error: error || "An error occurred generating the invite URL" };
  }

  return { success: true, data };
}

export async function validateInviteToken(token: string, userId?: string) {
  const { validationResult, shortCode, error } =
    await InviteService.validateInviteToken(token, userId);

  if (error) {
    return {
      validationResult: validationResult,
      shortCode: null,
      error: error || "An error occurred validating the invite token",
    };
  }

  return { validationResult, shortCode, error };
}

export async function handleAcceptInvite(token: string, userId: string) {
  const { data, error } = await InviteService.acceptInvite(token, userId);

  if (error) {
    return {
      data: null,
      shortCode: null,
      error: error.message || "An error occurred accepting the invite",
    };
  }

  if (data) {
    // Fetch the league to get the short code
    const { LeagueService } = await import(
      "@/lib/services/league/leagues_service"
    );
    const { data: league, error: leagueError } = await LeagueService.getLeague(
      data.league_id
    );

    if (leagueError || !league) {
      return { data: null, shortCode: null, error: "Failed to fetch league information" };
    }

    return { data, shortCode: league.short_code, error: null };
  } else {
    return { data: null, shortCode: null, error: "An error occurred accepting the invite" };
  }
}
