'use server';

import { redirect } from 'next/navigation';
import { createClient } from '@/lib/database/server';
import { InvitationService } from '@/lib/services/invitation/invitation_service';
import { Invitation } from '@/lib/types/database_types';

export async function sendLeagueInvite(formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { error: 'You must be logged in to send invitations' };
  }

  const email = formData.get('email') as string;
  const leagueId = formData.get('leagueId') as string;

  if (!email || !leagueId) {
    return { error: 'Email and league ID are required' };
  }

  const invite: Invitation = {
    // id: is generated by the database
    league_id: leagueId,
    email,
    invited_by: user.id,
    // token: is generated by the database
    status: 'pending',
    // expires_at: is generated by the database
    // created_at: is generated by the database
  };

  const { data, error } = await InvitationService.createAndSendInvitation(invite);

  if (error) {
    return { error: error as string || 'An error occurred' };
  }

  return { success: true, data };
}

export async function handleInviteRedirect(token: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    redirect(`/login?invite=${token}`);
  }

  redirect(`/invite/${token}`);
}
