import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { AlertProvider } from "./components/Alert/AlertContext";
import { AlertContainer } from "./components/Alert/AlertContainer";
import { AuthModalProvider } from "./components/Auth/AuthModalContext";
import AuthModal from "./components/Auth/AuthModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AlertProvider>
          <AuthModalProvider>
            <Navbar />
            <AlertContainer />
            <AuthModal /> {/* This renders the modal when needed */}
            <main className="flex-1 pt-16">
              {children}
            </main>
          </AuthModalProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
