const CHARACTER_DATA = {
    "Mario": {
        "char_id": 0,
        "name": "Mario",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 6,
        "running_stat_bar": 5,
        "chemistry_table_id": 1,
        "chemistry": []
    },
    "Luigi": {
        "char_id": 1,
        "name": "Luigi",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 6,
        "running_stat_bar": 6,
        "chemistry_table_id": 2,
        "chemistry": []
    },
    "DK": {
        "char_id": 2,
        "name": "DK",
        "batting_stance": 1,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 7,
        "running_stat_bar": 4,
        "chemistry_table_id": 3,
        "chemistry": []
    },
    "Diddy": {
        "char_id": 3,
        "name": "Diddy",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 7,
        "pitching_stat_bar": 6,
        "running_stat_bar": 7,
        "chemistry_table_id": 4,
        "chemistry": []
    },
    "Peach": {
        "char_id": 4,
        "name": "Peach",
        "batting_stance": 0,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 7,
        "pitching_stat_bar": 8,
        "running_stat_bar": 5,
        "chemistry_table_id": 5,
        "chemistry": []
    },
    "Daisy": {
        "char_id": 5,
        "name": "Daisy",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 7,
        "running_stat_bar": 4,
        "chemistry_table_id": 6,
        "chemistry": []
    },
    "Yoshi": {
        "char_id": 6,
        "name": "Yoshi",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 4,
        "running_stat_bar": 9,
        "chemistry_table_id": 7,
        "chemistry": []
    },
    "Baby Mario": {
        "char_id": 7,
        "name": "Baby Mario",
        "batting_stance": 0,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 5,
        "running_stat_bar": 7,
        "chemistry_table_id": 8,
        "chemistry": []
    },
    "Baby Luigi": {
        "char_id": 8,
        "name": "Baby Luigi",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 2,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 5,
        "running_stat_bar": 8,
        "chemistry_table_id": 9,
        "chemistry": []
    },
    "Bowser": {
        "char_id": 9,
        "name": "Bowser",
        "batting_stance": 1,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 9,
        "fielding_stat_bar": 1,
        "pitching_stat_bar": 9,
        "running_stat_bar": 1,
        "chemistry_table_id": 10,
        "chemistry": []
    },
    "Wario": {
        "char_id": 10,
        "name": "Wario",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 3,
        "chemistry_table_id": 11,
        "chemistry": []
    },
    "Waluigi": {
        "char_id": 11,
        "name": "Waluigi",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 9,
        "running_stat_bar": 4,
        "chemistry_table_id": 12,
        "chemistry": []
    },
    "Koopa(G)": {
        "char_id": 12,
        "name": "Koopa(G)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 13,
        "chemistry": []
    },
    "Toad(R)": {
        "char_id": 13,
        "name": "Toad(R)",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 6,
        "chemistry_table_id": 14,
        "chemistry": []
    },
    "Boo": {
        "char_id": 14,
        "name": "Boo",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 2,
        "pitching_stat_bar": 8,
        "running_stat_bar": 4,
        "chemistry_table_id": 15,
        "chemistry": []
    },
    "Toadette": {
        "char_id": 15,
        "name": "Toadette",
        "batting_stance": 0,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 2,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 9,
        "chemistry_table_id": 16,
        "chemistry": []
    },
    "Shy Guy(R)": {
        "char_id": 16,
        "name": "Shy Guy(R)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 1,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 3,
        "running_stat_bar": 4,
        "chemistry_table_id": 17,
        "chemistry": []
    },
    "Birdo": {
        "char_id": 17,
        "name": "Birdo",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 18,
        "chemistry": []
    },
    "Monty": {
        "char_id": 18,
        "name": "Monty",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 3,
        "running_stat_bar": 7,
        "chemistry_table_id": 19,
        "chemistry": []
    },
    "Bowser Jr": {
        "char_id": 19,
        "name": "Bowser Jr",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 1,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 5,
        "running_stat_bar": 4,
        "chemistry_table_id": 20,
        "chemistry": []
    },
    "Paratroopa(R)": {
        "char_id": 20,
        "name": "Paratroopa(R)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 6,
        "chemistry_table_id": 21,
        "chemistry": []
    },
    "Pianta(B)": {
        "char_id": 21,
        "name": "Pianta(B)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 3,
        "running_stat_bar": 2,
        "chemistry_table_id": 22,
        "chemistry": []
    },
    "Pianta(R)": {
        "char_id": 22,
        "name": "Pianta(R)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 7,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 3,
        "running_stat_bar": 1,
        "chemistry_table_id": 23,
        "chemistry": []
    },
    "Pianta(Y)": {
        "char_id": 23,
        "name": "Pianta(Y)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 4,
        "running_stat_bar": 1,
        "chemistry_table_id": 24,
        "chemistry": []
    },
    "Noki(B)": {
        "char_id": 24,
        "name": "Noki(B)",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 7,
        "chemistry_table_id": 25,
        "chemistry": []
    },
    "Noki(R)": {
        "char_id": 25,
        "name": "Noki(R)",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 6,
        "chemistry_table_id": 26,
        "chemistry": []
    },
    "Noki(G)": {
        "char_id": 26,
        "name": "Noki(G)",
        "batting_stance": 1,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 4,
        "running_stat_bar": 6,
        "chemistry_table_id": 27,
        "chemistry": []
    },
    "Bro(H)": {
        "char_id": 27,
        "name": "Bro(H)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 3,
        "chemistry_table_id": 28,
        "chemistry": []
    },
    "Toadsworth": {
        "char_id": 28,
        "name": "Toadsworth",
        "batting_stance": 0,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 29,
        "chemistry": []
    },
    "Toad(B)": {
        "char_id": 29,
        "name": "Toad(B)",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 7,
        "chemistry_table_id": 30,
        "chemistry": []
    },
    "Toad(Y)": {
        "char_id": 30,
        "name": "Toad(Y)",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 4,
        "running_stat_bar": 6,
        "chemistry_table_id": 31,
        "chemistry": []
    },
    "Toad(G)": {
        "char_id": 31,
        "name": "Toad(G)",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 6,
        "chemistry_table_id": 32,
        "chemistry": []
    },
    "Toad(P)": {
        "char_id": 32,
        "name": "Toad(P)",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 5,
        "chemistry_table_id": 33,
        "chemistry": []
    },
    "Magikoopa(B)": {
        "char_id": 33,
        "name": "Magikoopa(B)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 8,
        "pitching_stat_bar": 2,
        "running_stat_bar": 2,
        "chemistry_table_id": 34,
        "chemistry": []
    },
    "Magikoopa(R)": {
        "char_id": 34,
        "name": "Magikoopa(R)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 8,
        "pitching_stat_bar": 2,
        "running_stat_bar": 1,
        "chemistry_table_id": 35,
        "chemistry": []
    },
    "Magikoopa(G)": {
        "char_id": 35,
        "name": "Magikoopa(G)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 8,
        "pitching_stat_bar": 3,
        "running_stat_bar": 1,
        "chemistry_table_id": 36,
        "chemistry": []
    },
    "Magikoopa(Y)": {
        "char_id": 36,
        "name": "Magikoopa(Y)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 8,
        "pitching_stat_bar": 4,
        "running_stat_bar": 1,
        "chemistry_table_id": 37,
        "chemistry": []
    },
    "King Boo": {
        "char_id": 37,
        "name": "King Boo",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 7,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 5,
        "running_stat_bar": 3,
        "chemistry_table_id": 38,
        "chemistry": []
    },
    "Petey": {
        "char_id": 38,
        "name": "Petey",
        "batting_stance": 1,
        "character_class": 1,
        "fielding_arm": 1,
        "batting_stat_bar": 9,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 4,
        "running_stat_bar": 1,
        "chemistry_table_id": 39,
        "chemistry": []
    },
    "Dixie": {
        "char_id": 39,
        "name": "Dixie",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 2,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 5,
        "running_stat_bar": 6,
        "chemistry_table_id": 40,
        "chemistry": []
    },
    "Goomba": {
        "char_id": 40,
        "name": "Goomba",
        "batting_stance": 0,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 5,
        "chemistry_table_id": 41,
        "chemistry": []
    },
    "Paragoomba": {
        "char_id": 41,
        "name": "Paragoomba",
        "batting_stance": 0,
        "character_class": 2,
        "fielding_arm": 0,
        "batting_stat_bar": 3,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 2,
        "running_stat_bar": 7,
        "chemistry_table_id": 42,
        "chemistry": []
    },
    "Koopa(R)": {
        "char_id": 42,
        "name": "Koopa(R)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 0,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 4,
        "running_stat_bar": 3,
        "chemistry_table_id": 43,
        "chemistry": []
    },
    "Paratroopa(G)": {
        "char_id": 43,
        "name": "Paratroopa(G)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 0,
        "batting_stat_bar": 2,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 3,
        "running_stat_bar": 6,
        "chemistry_table_id": 44,
        "chemistry": []
    },
    "Shy Guy(B)": {
        "char_id": 44,
        "name": "Shy Guy(B)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 1,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 3,
        "running_stat_bar": 5,
        "chemistry_table_id": 45,
        "chemistry": []
    },
    "Shy Guy(Y)": {
        "char_id": 45,
        "name": "Shy Guy(Y)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 1,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 46,
        "chemistry": []
    },
    "Shy Guy(G)": {
        "char_id": 46,
        "name": "Shy Guy(G)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 1,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 5,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 47,
        "chemistry": []
    },
    "Shy Guy(Bk)": {
        "char_id": 47,
        "name": "Shy Guy(Bk)",
        "batting_stance": 1,
        "character_class": 0,
        "fielding_arm": 1,
        "batting_stat_bar": 4,
        "fielding_stat_bar": 6,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 48,
        "chemistry": []
    },
    "Dry Bones(Gy)": {
        "char_id": 48,
        "name": "Dry Bones(Gy)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 4,
        "running_stat_bar": 4,
        "chemistry_table_id": 49,
        "chemistry": []
    },
    "Dry Bones(G)": {
        "char_id": 49,
        "name": "Dry Bones(G)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 4,
        "running_stat_bar": 3,
        "chemistry_table_id": 50,
        "chemistry": []
    },
    "Dry Bones(R)": {
        "char_id": 50,
        "name": "Dry Bones(R)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 6,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 4,
        "running_stat_bar": 3,
        "chemistry_table_id": 51,
        "chemistry": []
    },
    "Dry Bones(B)": {
        "char_id": 51,
        "name": "Dry Bones(B)",
        "batting_stance": 1,
        "character_class": 3,
        "fielding_arm": 1,
        "batting_stat_bar": 5,
        "fielding_stat_bar": 4,
        "pitching_stat_bar": 4,
        "running_stat_bar": 3,
        "chemistry_table_id": 52,
        "chemistry": []
    },
    "Bro(F)": {
        "char_id": 52,
        "name": "Bro(F)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 2,
        "chemistry_table_id": 53,
        "chemistry": []
    },
    "Bro(B)": {
        "char_id": 53,
        "name": "Bro(B)",
        "batting_stance": 0,
        "character_class": 1,
        "fielding_arm": 0,
        "batting_stat_bar": 8,
        "fielding_stat_bar": 3,
        "pitching_stat_bar": 3,
        "running_stat_bar": 3,
        "chemistry_table_id": 54,
        "chemistry": []
    }
} as const;


export function getCharacterData(name: string) {
    return CHARACTER_DATA[name as keyof typeof CHARACTER_DATA];
}
